name: chart_q
description: ChartQ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10
  flutter_widget_from_html: ^0.15.3
  freezed_annotation: ^2.4.4
  go_router: ^14.6.1
  json_annotation: ^4.8.1
  logger: ^2.5.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
